### ISSUE TITLE
error when compile

### ISSUE THREAD

**Issue by lesun90** [adafruit/adafruit-bluefruit-le-desktop#15]
I get error at step gulp package 
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\youbot\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Users\\youbot\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=0.30.4" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd c:\5k\app\node_modules\noble\node_modules\bluetooth-hci-socket\node_modules\usb
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
[23:57:37] 'rebuild-usb' errored after 20 s
[23:57:37] Error: Command `cd app/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb && node-gyp rebuild --target=0.30.4 --dist-url=https://atom.io/download/atom-shell` exited with code 1
    at ChildProcess.<anonymous> (c:\5k\node_modules\gulp-run\lib\command.js:145:15)
    at ChildProcess.g (events.js:199:16)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

I am using windows 10. The binary package work well on my machine. I want to modify your project to fit my purpose but I cannot compile it. I really dont know how to fix. Help me please. Thank you.

**Comment by tdicola** [comment]
Oh I think this is the same question as in the forums here: https://forums.adafruit.com/viewtopic.php?f=19&t=81471  Let's followup on the forums--it looks like you might need to double check all the steps for compiling a native node JS module is working for you (check the node-gyp github repo for good instructions).
