### ISSUE TITLE
A JavaScript error occured in the main process

### ISSUE THREAD

**Issue by nicholasbennet** [adafruit/adafruit-bluefruit-le-desktop#34]
Following error message while running app in OS X 10.15.4

`Uncaught Exception:
TypeError: Cannot read property 'toString' of undefined
    at null.<anonymous> (/private/var/folders/80/_xqwbfy12d9g7gx1k2ry05f40000gp/T/AppTranslocation/365ABDBE-06AD-4050-9D0F-128D7240BF6F/d/able.app/Contents/Resources/app.asar/node_modules/noble/lib/mac/yosemite.js:208:44)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/private/var/folders/80/_xqwbfy12d9g7gx1k2ry05f40000gp/T/AppTranslocation/365ABDBE-06AD-4050-9D0F-128D7240BF6F/d/able.app/Contents/Resources/app.asar/node_modules/noble/lib/mac/yosemite.js:35:8)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/private/var/folders/80/_xqwbfy12d9g7gx1k2ry05f40000gp/T/AppTranslocation/365ABDBE-06AD-4050-9D0F-128D7240BF6F/d/able.app/Contents/Resources/app.asar/node_modules/noble/lib/mac/yosemite.js:17:59)
    at emitOne (events.js:77:13)
    at XpcConnection.emit (events.js:169:7)`

**Comment by falkorichter** [comment]
same here 
<img width="532" alt="Screenshot 2020-09-25 at 16 32 09" src="https://user-images.githubusercontent.com/50506/94279654-b6576680-ff4c-11ea-9e30-7e30d3bb79f3.png">

**Comment by gymnae** [comment]
Also have this issue
